name: base
channels: 
  - pytorch
  - conda-forge
dependencies:
  - pip
  - cudatoolkit=11.1
  - pip:
    - torch==1.8.0+cu111 
    - torchvision==0.9.0+cu111
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - pandas
    - matplotlib
    - scikit-image
    - black
    - isort
    - flake8
    - tdqm
    - jupyter
    - ipykernel
    - imageio
    - plotly
    - opencv-python
    - tensorboard
    - plyfile
    - celluloid
    - attrdict
    - moviepy
    - tensorboard
    - networkx
    - open3d
    - trimesh
    - open3d